# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Harness-FileFilter
version:      0.01
version_from: lib/Test/Harness/FileFilter.pm
installdirs:  site
requires:
    File::Spec:                    0
    Test::Harness:                 0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
